// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgsppgtbqllsobvilwyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnc3BwZ3RicWxsc29idmlsd3l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTgzNzMsImV4cCI6MjA3MDAzNDM3M30.xXyEDQlPQbpzGP_KlQ9NGaastARli7Hb2rui2AwugP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});